<?php
# This file was automatically generated by the MediaWiki 1.44.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if (!defined('MEDIAWIKI')) {
        exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = getenv('WGSITENAME');

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = getenv('WGSERVER');

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
        '1x' => "$wgResourceBasePath/images/logos/wiki.svg",
        'icon' => "$wgResourceBasePath/images/logos/wiki.svg",
];
$wgFavicon = "$wgResourceBasePath/images/logos/favicon.ico";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "webmestre@wikiromandie.org";
$wgPasswordSender = "no-reply@wikiromandie.org";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = getenv('WGDBTYPE');
$wgDBserver = getenv('WGDBSERVER');
$wgDBname = getenv('WGDBNAME');
$wgDBuser = getenv('WGDBUSER');
$wgDBpassword = getenv('WGDBPASSWORD');

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = false;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";
# More file extensions allowed for upload
$wgFileExtensions[] = 'mp4';
$wgFileExtensions[] = 'mov';

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = true;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "fr";

# Time zone
$wgLocaltimezone = "Europe/Zurich";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
$wgCacheDirectory = "$IP/cache";

$wgSecretKey = getenv('WGSECRETKEY');

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = getenv('WGUPGRADEKEY');

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin('MinervaNeue');
wfLoadSkin('MonoBook');
wfLoadSkin('Timeless');
wfLoadSkin('Vector');


# End of automatically generated settings.
# Add more configuration options below.


#==================================================================
#============ MAIL ============
# SMTP
$wgSMTP = [
        'host'      => getenv('SMTPHOST'),
        'IDHost'    => getenv('SMTPIDHOST'),
        'localhost' => getenv('SMTPLOCALHOST'),
        'port'      => getenv('SMTPPORT'),
        'auth'      => true,
        'username'  => getenv('SMTPUSERNAME'),
        'password'  => getenv('SMTPPASSWORD')
];

#==================================================================
#============ Indexation ============
$wgNamespaceRobotPolicies[NS_USER] = 'noindex, nofollow';
$wgNamespaceRobotPolicies[NS_USER_TALK] = 'noindex, nofollow';
$wgNamespaceRobotPolicies[NS_TEMPLATE] = 'noindex, nofollow';
$wgNamespaceRobotPolicies[NS_TEMPLATE_TALK] = 'noindex, nofollow';
$wgNamespaceRobotPolicies[NS_CATEGORY] = 'noindex, nofollow';
$wgNamespaceRobotPolicies[NS_CATEGORY_TALK] = 'noindex, nofollow';
$wgNamespaceRobotPolicies[NS_PROJECT] = 'noindex, nofollow';
$wgNamespaceRobotPolicies[NS_PROJECT_TALK] = 'noindex, nofollow';
$wgNamespaceRobotPolicies[NS_FILE] = 'noindex, nofollow';
$wgNamespaceRobotPolicies[NS_FILE_TALK] = 'noindex, nofollow';
$wgNamespaceRobotPolicies[NS_HELP] = 'noindex, nofollow';
$wgNamespaceRobotPolicies[NS_HELP_TALK] = 'noindex, nofollow';
$wgNamespaceRobotPolicies[NS_MEDIAWIKI] = 'noindex, nofollow';
$wgNamespaceRobotPolicies[NS_MEDIAWIKI_TALK] = 'noindex, nofollow';


#==================================================================
#============ Extensions ============
# Nuke
wfLoadExtension('Nuke');

# VisualEditor
wfLoadExtension('VisualEditor');

# Captcha
wfLoadExtensions(['ConfirmEdit']);
wfLoadExtensions(['ConfirmEdit/QuestyCaptcha']);
$wgCaptchaClass = 'QuestyCaptcha';

$wgCaptchaQuestions = [
        "Combien de cantons ont le français comme langue officielle? <a href=\"https://wikiromandie.org/index.php?title=Romandie\" alt=\"Cantons parlant le français\">Cantons de la Romandie</a><br><i>Écrire la réponse en toute lettres minuscule.</i>" => "sept"
];

# Infobox
wfLoadExtension('Scribunto');
$wgScribuntoDefaultEngine = 'luastandalone';

# <ref> via Cite
wfLoadExtension('Cite');

# ParserFunctions
wfLoadExtension('ParserFunctions');
$wgPFEnableStringFunctions = true;

# TemplateStyles
wfLoadExtension('TemplateStyles');

# WikiEditor
wfLoadExtension('WikiEditor');

# SyntaxHighlight_GeSHi
wfLoadExtension('SyntaxHighlight_GeSHi');

# CodeEditor
wfLoadExtension('CodeEditor');
$wgDefaultUserOptions['usebetatoolbar'] = 1; // user option provided by WikiEditor extension

#=============================================================
# JsonConfig
wfLoadExtension('JsonConfig');

$wgJsonConfigEnableLuaSupport = true; // required to use JsonConfig in Lua
$wgJsonConfigModels['Tabular.JsonConfig'] = 'JsonConfig\JCTabularContent';
$wgJsonConfigs['Tabular.JsonConfig'] = [
        'namespace' => 486,
        'nsName' => 'Data',
        // page name must end in .tab, and contain at least one symbol
        'pattern' => '/.\.tab$/',
        'license' => 'CC0-1.0',
        'isLocal' => false,
];

$wgJsonConfigModels['Map.JsonConfig'] = 'JsonConfig\JCMapDataContent';
$wgJsonConfigs['Map.JsonConfig'] = [
        'namespace' => 486,
        'nsName' => 'Data',
        // page name must end in .map, and contain at least one symbol
        'pattern' => '/.\.map$/',
        'license' => 'CC0-1.0',
        'isLocal' => false,
];
$wgJsonConfigInterwikiPrefix = "commons";

$wgJsonConfigs['Tabular.JsonConfig']['remote'] = [
        'url' => 'https://commons.wikimedia.org/w/api.php'
];
$wgJsonConfigs['Map.JsonConfig']['remote'] = [
        'url' => 'https://commons.wikimedia.org/w/api.php'
];
#=============================================================

# Wikibase
wfLoadExtension('WikibaseRepository', "$IP/extensions/Wikibase/extension-repo.json");
require_once "$IP/extensions/Wikibase/repo/ExampleSettings.php";

wfLoadExtension('WikibaseClient', "$IP/extensions/Wikibase/extension-client.json");
require_once "$IP/extensions/Wikibase/client/ExampleSettings.php";
$wgWBRepoSettings['enableEntitySearchUI'] = false;

# TemplateData
wfLoadExtension('TemplateData');

# Elastica -- https://www.mediawiki.org/wiki/Extension:Elastica
wfLoadExtension('Elastica');

# CirrusSearch -- https://www.mediawiki.org/wiki/Extension:CirrusSearch
wfLoadExtension('CirrusSearch');
$wgCirrusSearchServers = [getenv('ELASTICSEARCHSERVER')];
$wgSearchType = 'CirrusSearch';
$wgCirrusSearchUsePhraseSuggest = true;
$wgCirrusSearchUseCompletionSuggester = true;
$wgCirrusSearchEnablePrefixSearch = true;
$wgCirrusSearchPrefixSearchStartsWithAnyWord = true;
$wgCirrusSearchCompletionSuggesterSubphrases = [
        'build' => true,
        'use' => true,
        'type' => 'anywords',
        'limit' => 10,
];
$wgCirrusSearchCompletionSettings = 'fuzzy-subphrases';


# EmbedVideo -- https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo
wfLoadExtension('EmbedVideo');

# OpenGraphMeta -- https://www.mediawiki.org/wiki/Extension:OpenGraphMeta
wfLoadExtension('OpenGraphMeta');

# Description2 -- https://www.mediawiki.org/wiki/Extension:Description2
wfLoadExtension('Description2');
$wgEnableMetaDescriptionFunctions = true;

# SemanticWiki -- https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/INSTALL.md
wfLoadExtension('SemanticMediaWiki');
enableSemantics(getenv('WGSITENAME'));

# PageImages
wfLoadExtension('PageImages');
$wgPageImagesOpenGraphFallbackImage = '/images/logos/wiki.svg';

#==================================================================
#= GROUPES

# Groupe 0 : Pas connecté

$wgGroupPermissions['*']['read'] = true;              // Lire
$wgGroupPermissions['*']['edit'] = false;              // Modifier article
$wgGroupPermissions['*']['createpage'] = false;        // Créer nouvel article
$wgGroupPermissions['*']['editmytalk'] = false;        // Débattre (pages de discussion)
$wgGroupPermissions['*']['talk'] = false;              // Débattre (discussion publique)
$wgGroupPermissions['*']['votepages'] = false;         // Voter (si plugin nécessaire)
$wgGroupPermissions['*']['delete'] = false;           // Supprimer page article
$wgGroupPermissions['*']['createportal'] = false;      // Créer portail (si extension nécessaire)
$wgGroupPermissions['*']['editportal'] = false;        // Modifier portail (si extension nécessaire)
$wgGroupPermissions['*']['protect'] = false;          // Activer sécurité page (protéger page)
$wgGroupPermissions['*']['block'] = false;            // Bloquer utilisateur
$wgGroupPermissions['*']['undelete'] = false;         // Restaurer version précédente


# Groupe 1 : Connecté, pas confirmé par mail

$wgGroupPermissions['user']['read'] = true;              // Lire
$wgGroupPermissions['user']['edit'] = false;              // Modifier article
$wgGroupPermissions['user']['createpage'] = false;        // Créer nouvel article
$wgGroupPermissions['user']['editmytalk'] = false;        // Débattre (pages de discussion)
$wgGroupPermissions['user']['talk'] = false;              // Débattre (discussion publique)
$wgGroupPermissions['user']['votepages'] = false;         // Voter (si plugin nécessaire)
$wgGroupPermissions['user']['delete'] = false;           // Supprimer page article
$wgGroupPermissions['user']['createportal'] = false;      // Créer portail (si extension nécessaire)
$wgGroupPermissions['user']['editportal'] = false;        // Modifier portail (si extension nécessaire)
$wgGroupPermissions['user']['protect'] = false;          // Activer sécurité page (protéger page)
$wgGroupPermissions['user']['block'] = false;            // Bloquer utilisateur
$wgGroupPermissions['user']['undelete'] = false;         // Restaurer version précédente


# Groupe 2 : Connecté, confirmé par mail

$wgGroupPermissions['confirmed']['read'] = true;              // Lire
$wgGroupPermissions['confirmed']['edit'] = true;              // Modifier article
$wgGroupPermissions['confirmed']['createpage'] = false;        // Créer nouvel article
$wgGroupPermissions['confirmed']['editmytalk'] = false;        // Débattre (pages de discussion)
$wgGroupPermissions['confirmed']['talk'] = false;              // Débattre (discussion publique)
$wgGroupPermissions['confirmed']['votepages'] = false;         // Voter (si plugin nécessaire)
$wgGroupPermissions['confirmed']['delete'] = false;           // Supprimer page article
$wgGroupPermissions['confirmed']['createportal'] = false;      // Créer portail (si extension nécessaire)
$wgGroupPermissions['confirmed']['editportal'] = false;        // Modifier portail (si extension nécessaire)
$wgGroupPermissions['confirmed']['protect'] = false;          // Activer sécurité page (protéger page)
$wgGroupPermissions['confirmed']['block'] = false;            // Bloquer utilisateur
$wgGroupPermissions['confirmed']['undelete'] = false;         // Restaurer version précédente


# Groupe 3.1 : Individu

$wgGroupPermissions['individu']['read'] = true;              // Lire
$wgGroupPermissions['individu']['edit'] = true;              // Modifier article
$wgGroupPermissions['individu']['createpage'] = true;        // Créer nouvel article
$wgGroupPermissions['individu']['editmytalk'] = true;        // Débattre (pages de discussion)
$wgGroupPermissions['individu']['talk'] = true;              // Débattre (discussion publique)
$wgGroupPermissions['individu']['votepages'] = true;         // Voter (si plugin nécessaire)
$wgGroupPermissions['individu']['delete'] = false;           // Supprimer page article
$wgGroupPermissions['individu']['createportal'] = false;      // Créer portail (si extension nécessaire)
$wgGroupPermissions['individu']['editportal'] = true;        // Modifier portail (si extension nécessaire)
$wgGroupPermissions['individu']['protect'] = true;          // Activer sécurité page (protéger page)
$wgGroupPermissions['individu']['block'] = false;            // Bloquer utilisateur
$wgGroupPermissions['individu']['undelete'] = false;         // Restaurer version précédente


# Groupe 3.2 : Association

$wgGroupPermissions['association']['read'] = true;              // Lire
$wgGroupPermissions['association']['edit'] = true;              // Modifier article
$wgGroupPermissions['association']['createpage'] = true;        // Créer nouvel article
$wgGroupPermissions['association']['editmytalk'] = true;        // Débattre (pages de discussion)
$wgGroupPermissions['association']['talk'] = true;              // Débattre (discussion publique)
$wgGroupPermissions['association']['votepages'] = true;         // Voter (si plugin nécessaire)
$wgGroupPermissions['association']['delete'] = false;           // Supprimer page article
$wgGroupPermissions['association']['createportal'] = false;      // Créer portail (si extension nécessaire)
$wgGroupPermissions['association']['editportal'] = true;        // Modifier portail (si extension nécessaire)
$wgGroupPermissions['association']['protect'] = true;          // Activer sécurité page (protéger page)
$wgGroupPermissions['association']['block'] = false;            // Bloquer utilisateur
$wgGroupPermissions['association']['undelete'] = false;         // Restaurer version précédente


# Groupe 3.3 : Entreprise

$wgGroupPermissions['entreprise']['read'] = true;              // Lire
$wgGroupPermissions['entreprise']['edit'] = true;              // Modifier article
$wgGroupPermissions['entreprise']['createpage'] = true;        // Créer nouvel article
$wgGroupPermissions['entreprise']['editmytalk'] = true;        // Débattre (pages de discussion)
$wgGroupPermissions['entreprise']['talk'] = true;              // Débattre (discussion publique)
$wgGroupPermissions['entreprise']['votepages'] = false;         // Voter (si plugin nécessaire)
$wgGroupPermissions['entreprise']['delete'] = false;           // Supprimer page article
$wgGroupPermissions['entreprise']['createportal'] = false;      // Créer portail (si extension nécessaire)
$wgGroupPermissions['entreprise']['editportal'] = true;        // Modifier portail (si extension nécessaire)
$wgGroupPermissions['entreprise']['protect'] = true;          // Activer sécurité page (protéger page)
$wgGroupPermissions['entreprise']['block'] = false;            // Bloquer utilisateur
$wgGroupPermissions['entreprise']['undelete'] = false;         // Restaurer version précédente


# Groupe 3.4 : État

$wgGroupPermissions['etat']['read'] = true;              // Lire
$wgGroupPermissions['etat']['edit'] = true;              // Modifier article
$wgGroupPermissions['etat']['createpage'] = true;        // Créer nouvel article
$wgGroupPermissions['etat']['editmytalk'] = true;        // Débattre (pages de discussion)
$wgGroupPermissions['etat']['talk'] = true;              // Débattre (discussion publique)
$wgGroupPermissions['etat']['votepages'] = false;         // Voter (si plugin nécessaire)
$wgGroupPermissions['etat']['delete'] = false;           // Supprimer page article
$wgGroupPermissions['etat']['createportal'] = false;      // Créer portail (si extension nécessaire)
$wgGroupPermissions['etat']['editportal'] = true;        // Modifier portail (si extension nécessaire)
$wgGroupPermissions['etat']['protect'] = true;          // Activer sécurité page (protéger page)
$wgGroupPermissions['etat']['block'] = false;            // Bloquer utilisateur
$wgGroupPermissions['etat']['undelete'] = false;         // Restaurer version précédente

# Groupe 3.5 : Admin contenu

$wgGroupPermissions['admincontenu']['read'] = true;              // Lire
$wgGroupPermissions['admincontenu']['edit'] = true;              // Modifier article
$wgGroupPermissions['admincontenu']['createpage'] = true;        // Créer nouvel article
$wgGroupPermissions['admincontenu']['editmytalk'] = true;        // Débattre (pages de discussion)
$wgGroupPermissions['admincontenu']['talk'] = false;              // Débattre (discussion publique)
$wgGroupPermissions['admincontenu']['votepages'] = false;         // Voter (si plugin nécessaire)
$wgGroupPermissions['admincontenu']['delete'] = true;           // Supprimer page article
$wgGroupPermissions['admincontenu']['createportal'] = true;      // Créer portail (si extension nécessaire)
$wgGroupPermissions['admincontenu']['editportal'] = true;        // Modifier portail (si extension nécessaire)
$wgGroupPermissions['admincontenu']['protect'] = true;          // Activer sécurité page (protéger page)
$wgGroupPermissions['admincontenu']['block'] = true;            // Bloquer utilisateur
$wgGroupPermissions['admincontenu']['undelete'] = true;         // Restaurer version précédente
